# Generated by Django 3.0.8 on 2020-08-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='collections',
            name='movies',
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_uuid', models.CharField(max_length=50)),
                ('genre', models.ManyToManyField(blank=True, related_name='movie', to='movie.Genres')),
            ],
        ),
        migrations.AddField(
            model_name='collections',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='collection', to='movie.Movies'),
        ),
    ]
