# Generated by Django 3.0.8 on 2020-07-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitiesm',
            name='alpha_two_code',
            field=models.CharField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitiesm',
            name='country',
            field=models.CharField(default='United States', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitiesm',
            name='domain',
            field=models.CharField(default='acu.edu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitiesm',
            name='name',
            field=models.CharField(default='Abilene Christian University', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitiesm',
            name='web_page',
            field=models.URLField(default='http://www.acu.edu/'),
            preserve_default=False,
        ),
    ]
